"""Schema und Kennwertdefinitionen fuer Excel-Auswertungen."""

PLOT_SUBDIR_EXCEL = "excel"

METRIC_DEFINITIONS = {
    "max_q_heat": ("zone_energy_q_heat", "max"),
    "min_q_heat": ("zone_energy_q_heat", "min"),
    "max_q_cool": ("zone_energy_q_cool", "max"),
    "min_q_cool": ("zone_energy_q_cool", "min"),
    "max_q_occ": ("zone_energy_q_occ", "max"),
    "max_q_loss": ("zone_energy_q_loss", "max"),
    "max_q_equip": ("zone_energy_q_equip", "max"),
    "max_co2": ("iaq_xco2vol", "max"),
    "mean_co2": ("iaq_xco2vol", "mean"),
    "max_tair": ("temperatures_tairmean", "max"),
    "min_tair": ("temperatures_tairmean", "min"),
    "max_top": ("temperatures_top", "max"),
    "min_top": ("temperatures_top", "min"),
    "mean_top": ("temperatures_top", "mean"),
    "max_relhum": ("iaq_relhum", "max"),
    "min_relhum": ("iaq_relhum", "min"),
    "mean_relhum": ("iaq_relhum", "mean"),
    "max_air_age": ("iaq_air_age", "max"),
}

OUTPUT_COLUMNS = [
    "Zone",
    "Group",
    "Zone multiplier, M",
    "Min temp., °C",
    "Max temp., °C",
    "Min op temp., °C",
    "Max op temp., °C",
    "Room unit heat, kWh",
    "Room unit heat, kWh/m2",
    "Max heat supplied, W/m2",
    "Room unit heat, W/m2",
    "Max heat removed, W/m2",
    "Room unit cool, kWh",
    "Room unit cool, kWh/m2",
    "Room unit cool, W/m2",
    "Dryvent cool, W/m2",
    "Max sup airflow, L/s m2",
    "Max rtn airflow, L/s",
    "Max solar gain, W/m2",
    "Min rel hum, %",
    "Max rel hum, %",
    "Max CO2 ppm (vol)",
    "Max PPD, %",
    "Max age of air, h",
    "In use, h",
    "h of T_op>25, h",
    "h of T_op>27, h",
    "Occ. hours, h PDH, h",
    "Unmet hours (cooling)",
    "Unmet hours (heating)",
    "DIN 4108-2 over-temperature degree hours, h Deg-C",
]

COLUMN_RENAME = {
    "room": "Zone",
    "variant": "Group",
    "row_count": "In use, h",
    "min_tair": "Min temp., °C",
    "max_tair": "Max temp., °C",
    "min_top": "Min op temp., °C",
    "max_top": "Max op temp., °C",
    "max_q_heat": "Max heat supplied, W/m2",
    "max_q_cool": "Max heat removed, W/m2",
    "min_relhum": "Min rel hum, %",
    "max_relhum": "Max rel hum, %",
    "max_co2": "Max CO2 ppm (vol)",
    "max_air_age": "Max age of air, h",
}
