"""Gebaeudemodul mit Demo-Spezifikation und lokaler Quelldiagnose."""

from .catalog_registry import (
    BUILDING_CATALOG_TYPES,
    USER_DRAFT_STATUS,
    BuildingCatalogRegistry,
    CatalogRecord,
    build_building_catalog_registry,
    create_user_catalog_draft,
)
from .demo_loader import (
    BUILDING_SPECIFICATION_OPTIONS,
    load_building_spec,
    load_business_integration_lod1_building_spec,
    load_demo_building_spec,
    load_named_building_specification,
    load_small_office_5z_endvariant_02_building_spec,
    load_small_office_lod1_building_spec,
)
from .diagnostics import (
    BuildingSourceDiagnostic,
    diagnose_building_source,
    scan_building_input_directory,
    scan_default_building_input_files,
)
from .excel_catalogs import (
    DEFAULT_BUILDING_EXCEL_CATALOGS,
    BuildingExcelCatalog,
    load_building_excel_catalog,
)
from .ifc_lite_import import (
    IfcLiteImportSummary,
    derive_ifc_lite_building_candidate,
)
from .local_catalogs import (
    DEFAULT_BUILDING_CATALOG_DIRECTORY,
    LocalCatalog,
    LocalCatalogValidationError,
    load_local_building_catalog,
)
from .models import (
    VALID_CONSTRUCTION_CODES,
    Assumption,
    BuildingInfo,
    BuildingInputDetailLevel,
    BuildingMaturityLevel,
    BuildingModelSpecification,
    BuildingModelVersion,
    Opening,
    PhysicalElement,
    ProjectInfo,
    ShadingDevice,
    SimpleEnvelopeInput,
    Space,
    Storey,
    building_specification_from_dict,
)
from .paths import (
    BUILDING_CAD_INPUT_DIR,
    BUILDING_DATA_DIR,
    BUILDING_DIAGNOSTICS_DIR,
    BUILDING_IFC_INPUT_DIR,
    BUILDING_RHINO_INPUT_DIR,
    BUSINESS_INTEGRATION_LOD1_BUILDING_SPEC_PATH,
    BUSINESS_INTEGRATION_REFERENCE_RHINO_FILENAME,
    BUSINESS_INTEGRATION_REFERENCE_RHINO_PATH,
    DEFAULT_DEMO_BUILDING_SPEC_PATH,
    FACHLICHER_TEIL_REFERENCE_IFC_FILENAME,
    FACHLICHER_TEIL_REFERENCE_IFC_PATH,
    MASTER_THESIS_REFERENCE_IFC_FILENAME,
    MASTER_THESIS_REFERENCE_IFC_PATH,
    SMALL_OFFICE_5Z_ENDVARIANT_02_BUILDING_SPEC_PATH,
    SMALL_OFFICE_LOD1_BUILDING_SPEC_PATH,
)
from .validation import validate_building_spec

__all__ = [
    "BUILDING_SPECIFICATION_OPTIONS",
    "DEFAULT_BUILDING_EXCEL_CATALOGS",
    "BuildingExcelCatalog",
    "BUILDING_DATA_DIR",
    "BUILDING_DIAGNOSTICS_DIR",
    "BUILDING_CAD_INPUT_DIR",
    "BUILDING_IFC_INPUT_DIR",
    "BUILDING_RHINO_INPUT_DIR",
    "BUSINESS_INTEGRATION_LOD1_BUILDING_SPEC_PATH",
    "BUSINESS_INTEGRATION_REFERENCE_RHINO_FILENAME",
    "BUSINESS_INTEGRATION_REFERENCE_RHINO_PATH",
    "DEFAULT_DEMO_BUILDING_SPEC_PATH",
    "FACHLICHER_TEIL_REFERENCE_IFC_FILENAME",
    "FACHLICHER_TEIL_REFERENCE_IFC_PATH",
    "MASTER_THESIS_REFERENCE_IFC_FILENAME",
    "MASTER_THESIS_REFERENCE_IFC_PATH",
    "SMALL_OFFICE_5Z_ENDVARIANT_02_BUILDING_SPEC_PATH",
    "SMALL_OFFICE_LOD1_BUILDING_SPEC_PATH",
    "VALID_CONSTRUCTION_CODES",
    "Assumption",
    "BuildingInfo",
    "BuildingInputDetailLevel",
    "BuildingMaturityLevel",
    "BuildingModelSpecification",
    "BuildingModelVersion",
    "BuildingSourceDiagnostic",
    "IfcLiteImportSummary",
    "Opening",
    "PhysicalElement",
    "ProjectInfo",
    "ShadingDevice",
    "SimpleEnvelopeInput",
    "Space",
    "Storey",
    "building_specification_from_dict",
    "diagnose_building_source",
    "derive_ifc_lite_building_candidate",
    "load_business_integration_lod1_building_spec",
    "load_building_spec",
    "load_demo_building_spec",
    "load_named_building_specification",
    "load_small_office_5z_endvariant_02_building_spec",
    "load_small_office_lod1_building_spec",
    "scan_building_input_directory",
    "scan_default_building_input_files",
    "validate_building_spec",
    "DEFAULT_BUILDING_CATALOG_DIRECTORY",
    "LocalCatalog",
    "LocalCatalogValidationError",
    "load_local_building_catalog",
    "load_building_excel_catalog",
    "BUILDING_CATALOG_TYPES",
    "USER_DRAFT_STATUS",
    "BuildingCatalogRegistry",
    "CatalogRecord",
    "build_building_catalog_registry",
    "create_user_catalog_draft",
]
