"""Grundpaket fuer Varianten-, Parameter- und Optionsmodelle."""

from .document_catalog import Document, import_documents
from .economic_analysis import (
    calculate_variant_costs,
    calculate_variant_costs_for_variants,
    export_variant_cost_results_csv,
    export_variant_cost_results_json,
    import_economic_assumptions,
)
from .finalization import (
    FinalizationResult,
    FinalVariantCatalog,
    FinalVariantCatalogEntry,
    VariantIdRegistry,
    VselVverMapping,
    finalize_vver_dimensioning,
    generate_final_variants,
)
from .finalization_payload import finalization_result_to_payload, variant_id_registry_from_payload
from .ida_export import export_ida_variant_structure, load_ida_export_settings
from .importing.catalog import import_catalog
from .material_catalog import Material, MaterialProperty, import_materials
from .naming import apply_variant_names, load_naming_rules
from .option_catalog import OptionSet, OptionValue
from .parameter_catalog import Parameter
from .product_catalog import Product, ProductProperty, import_products
from .project_studies import (
    CAPACITY_STRATEGY,
    OPTIMIZATION_DIRECTION_ID,
    REFERENCE_VARIANT_ID,
    SENSITIVITY_DIRECTION_ID,
    build_small_office_candidate_rows,
    candidate_simulation_setup,
    candidate_source_is_current,
    materialize_zonal_capacities,
    select_candidate_ids,
    small_office_source_fingerprint,
    small_office_study_case_rows,
    source_fingerprint,
    variation_specification_is_current,
    verify_candidate_rows,
)
from .reporting import export_variant_overview
from .selection import filter_variants_by_options, random_select_variants, select_variants_by_key
from .simulation_results import (
    collect_simulation_metrics,
    export_simulation_metrics_to_json,
    map_result_folders_to_variants,
)
from .small_office_v1 import (
    DEFAULT_SMALL_OFFICE_V1_STUDY_CONFIG,
    CapacityFactor,
    OccupancyScheduleCase,
    OptimizationCase,
    SensitivityCase,
    SetpointBand,
    SmallOfficeV1Study,
    WeatherSensitivityCase,
    build_small_office_v1_optimization_cases,
    build_small_office_v1_sensitivity_cases,
    load_small_office_v1_study,
    optimization_case_rows,
)
from .source_catalog import Source, import_sources
from .system_catalog import (
    DependencyRule,
    SystemTemplate,
    SystemTemplateValue,
    import_system_catalog,
    resolve_system_templates_for_variant,
)
from .variant_manager import Variant, VariantValue
from .workflow import (
    MAX_CATALOG_VARIANTS,
    VariantCandidate,
    VariantCatalog,
    VariantRule,
    VariantSelection,
    VariantVerification,
    VariantWorkflowResult,
    build_variant_workflow,
    catalog_rows,
    default_zone_rules,
    generate_selected_variants,
    rule_rows,
    select_catalog_candidates,
)

__all__ = [
    "DependencyRule",
    "FinalizationResult",
    "FinalVariantCatalog",
    "FinalVariantCatalogEntry",
    "DEFAULT_SMALL_OFFICE_V1_STUDY_CONFIG",
    "Document",
    "Material",
    "MaterialProperty",
    "OptionSet",
    "OptionValue",
    "OccupancyScheduleCase",
    "OptimizationCase",
    "Parameter",
    "Product",
    "ProductProperty",
    "Source",
    "SensitivityCase",
    "SetpointBand",
    "SmallOfficeV1Study",
    "SystemTemplate",
    "SystemTemplateValue",
    "Variant",
    "VariantIdRegistry",
    "VariantCandidate",
    "VariantCatalog",
    "VariantRule",
    "VariantSelection",
    "VariantVerification",
    "VariantWorkflowResult",
    "VariantValue",
    "WeatherSensitivityCase",
    "VselVverMapping",
    "build_small_office_candidate_rows",
    "candidate_source_is_current",
    "candidate_simulation_setup",
    "materialize_zonal_capacities",
    "CAPACITY_STRATEGY",
    "OPTIMIZATION_DIRECTION_ID",
    "REFERENCE_VARIANT_ID",
    "SENSITIVITY_DIRECTION_ID",
    "select_candidate_ids",
    "small_office_source_fingerprint",
    "small_office_study_case_rows",
    "source_fingerprint",
    "verify_candidate_rows",
    "variation_specification_is_current",
    "variant_id_registry_from_payload",
    "apply_variant_names",
    "build_variant_workflow",
    "build_small_office_v1_optimization_cases",
    "build_small_office_v1_sensitivity_cases",
    "catalog_rows",
    "calculate_variant_costs",
    "calculate_variant_costs_for_variants",
    "collect_simulation_metrics",
    "export_ida_variant_structure",
    "export_simulation_metrics_to_json",
    "export_variant_cost_results_csv",
    "export_variant_cost_results_json",
    "export_variant_overview",
    "default_zone_rules",
    "generate_selected_variants",
    "filter_variants_by_options",
    "finalize_vver_dimensioning",
    "generate_final_variants",
    "finalization_result_to_payload",
    "import_catalog",
    "import_documents",
    "import_economic_assumptions",
    "import_materials",
    "import_products",
    "import_sources",
    "import_system_catalog",
    "load_ida_export_settings",
    "load_naming_rules",
    "load_small_office_v1_study",
    "MAX_CATALOG_VARIANTS",
    "map_result_folders_to_variants",
    "random_select_variants",
    "optimization_case_rows",
    "resolve_system_templates_for_variant",
    "rule_rows",
    "select_catalog_candidates",
    "select_variants_by_key",
    "CapacityFactor",
]
