"""Wetterdatenmodul fuer TRY-Datensaetze."""

from .run_weather_analysis import (
    WeatherAnalysisResult,
    main_plot_template_weather,
    plot_template_weather,
    record_weather_release_decision,
    run_weather_analysis,
)
from .try_importer import TryImportResult, import_try_weather_file
from .weather_catalog import DEFAULT_WEATHER_DATASETS_CONFIG, WeatherCatalog, WeatherDataset, import_weather_catalog
from .weather_events import WeatherEvent, detect_critical_weather_events, weather_event_rows
from .weather_file_discovery import (
    DEFAULT_TRY_FILE_LOCATION_CONFIG,
    DEFAULT_WEATHER_INPUT_DIR,
    WeatherDiscoveryStatus,
    WeatherDiscoveryValidationResult,
    WeatherFileDiscovery,
    WeatherLocationMappingSuggestion,
    WeatherStagedInputFile,
    discover_weather_input_files,
    register_discovered_weather_dataset,
    stage_weather_input_file,
    suggest_weather_location_mapping,
    update_weather_file_discovery,
    validate_weather_file_discovery,
    weather_discovery_rows,
)
from .weather_imports import (
    DWD_TRY_URL,
    LOCAL_WEATHER_DATASETS_CONFIG,
    LOCAL_WEATHER_INPUT_DIR,
    WeatherDatasetImportDraft,
    WeatherDatasetImportResult,
    import_local_weather_dataset,
    suggest_weather_key,
    validate_weather_import_draft,
)
from .weather_location_resolution import (
    DEFAULT_WEATHER_GEODATA_CONFIG,
    TRY_SOURCE_CRS_EPSG,
    WGS84_EPSG,
    WeatherGeodataSource,
    WeatherLocationResolution,
    WeatherLocationResolutionStatus,
    resolve_weather_file_location,
    transform_try_coordinates,
)
from .weather_locations import (
    DEFAULT_WEATHER_LOCATIONS_CONFIG,
    WeatherLocation,
    WeatherLocationCatalog,
    WeatherRegion,
    import_weather_location_catalog,
)
from .weather_metrics import WeatherMetrics, calculate_weather_metrics
from .weather_outputs import (
    DEFAULT_WEATHER_OUTPUT_ROOT,
    WeatherOutputPaths,
    build_weather_output_paths,
    write_weather_run_manifest,
)
from .weather_plots import (
    ALL_WEATHER_PLOTS,
    WEATHER_PLOT_CHOICES,
    WEATHER_PLOT_SPECS,
    WeatherPlotResult,
    WeatherPlotSpec,
    build_weather_plot,
    build_weather_plots,
)
from .weather_report import write_weather_report
from .weather_selection import (
    DEFAULT_WEATHER_SELECTION_STATE_PATH,
    WeatherActivationRecord,
    WeatherSelectionState,
    activate_weather_dataset,
    load_weather_selection_state,
    project_default_weather_dataset,
    save_weather_selection_state,
    set_project_default_weather_dataset,
)
from .weather_status import (
    WeatherDatasetStatus,
    WeatherFileStatus,
    WeatherImportCheckStatus,
    create_weather_import_id,
    infer_weather_start_year,
    inspect_weather_catalog_statuses,
    inspect_weather_dataset_status,
    stale_weather_status,
    weather_status_file_changed,
    weather_status_from_analysis_result,
    weather_statuses_by_key,
)
from .weather_validation import WeatherValidationReport, validate_weather_dataframe

__all__ = [
    "DEFAULT_WEATHER_DATASETS_CONFIG",
    "DEFAULT_WEATHER_LOCATIONS_CONFIG",
    "DEFAULT_TRY_FILE_LOCATION_CONFIG",
    "DEFAULT_WEATHER_INPUT_DIR",
    "DEFAULT_WEATHER_SELECTION_STATE_PATH",
    "DEFAULT_WEATHER_GEODATA_CONFIG",
    "DEFAULT_WEATHER_OUTPUT_ROOT",
    "DWD_TRY_URL",
    "LOCAL_WEATHER_DATASETS_CONFIG",
    "LOCAL_WEATHER_INPUT_DIR",
    "ALL_WEATHER_PLOTS",
    "WEATHER_PLOT_CHOICES",
    "WEATHER_PLOT_SPECS",
    "TryImportResult",
    "WeatherActivationRecord",
    "WeatherAnalysisResult",
    "WeatherCatalog",
    "WeatherDataset",
    "WeatherDatasetImportDraft",
    "WeatherDatasetImportResult",
    "WeatherDatasetStatus",
    "WeatherDiscoveryValidationResult",
    "WeatherDiscoveryStatus",
    "WeatherEvent",
    "WeatherFileStatus",
    "WeatherFileDiscovery",
    "WeatherImportCheckStatus",
    "WeatherGeodataSource",
    "WeatherLocation",
    "WeatherLocationCatalog",
    "WeatherLocationMappingSuggestion",
    "WeatherLocationResolution",
    "WeatherLocationResolutionStatus",
    "WeatherMetrics",
    "WeatherOutputPaths",
    "WeatherPlotResult",
    "WeatherPlotSpec",
    "WeatherRegion",
    "WeatherSelectionState",
    "WeatherStagedInputFile",
    "WeatherValidationReport",
    "TRY_SOURCE_CRS_EPSG",
    "WGS84_EPSG",
    "activate_weather_dataset",
    "build_weather_plot",
    "build_weather_plots",
    "build_weather_output_paths",
    "calculate_weather_metrics",
    "create_weather_import_id",
    "detect_critical_weather_events",
    "discover_weather_input_files",
    "infer_weather_start_year",
    "import_try_weather_file",
    "import_local_weather_dataset",
    "import_weather_catalog",
    "import_weather_location_catalog",
    "inspect_weather_catalog_statuses",
    "inspect_weather_dataset_status",
    "stale_weather_status",
    "weather_status_file_changed",
    "load_weather_selection_state",
    "main_plot_template_weather",
    "plot_template_weather",
    "project_default_weather_dataset",
    "record_weather_release_decision",
    "register_discovered_weather_dataset",
    "resolve_weather_file_location",
    "run_weather_analysis",
    "save_weather_selection_state",
    "set_project_default_weather_dataset",
    "stage_weather_input_file",
    "suggest_weather_location_mapping",
    "suggest_weather_key",
    "transform_try_coordinates",
    "update_weather_file_discovery",
    "validate_weather_import_draft",
    "validate_weather_file_discovery",
    "validate_weather_dataframe",
    "weather_event_rows",
    "weather_discovery_rows",
    "weather_status_from_analysis_result",
    "weather_statuses_by_key",
    "write_weather_report",
    "write_weather_run_manifest",
]
